
services:
  db:
    container_name: database
    image: "postgres:17.5-alpine3.21"
    environment:
      - POSTGRES_DB=danieldoescocktails
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - db_data:/var/lib/postresql/data
      - ./database/schema/postgres.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    secrets:
      - db-password
    healthcheck:
      test: ["CMD", "pg_isready", "-ddanieldoescocktails", "-Udaniel"]
      interval: 60s
      timeout: 10s
      retries: 3

  backend:
    depends_on:
      - db
    container_name: backend
    image: "danieldoescocktails-backend:latest"
    environment:
      - CORS-ALLOW-ORIGINS=["http://localhost","http://danieldoescocktails.com","http://www.danieldoescocktails.com"]
    env_file: ".secrets/postgres-variables.env"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "python", "/opt/danieldoescocktails/backend/healthcheck.py"]
      interval: 60s

  frontend:
    depends_on:
      - backend
    container_name: frontend
    image: "danieldoescocktails-frontend:latest"
    ports:
      - "80:80"


volumes:
  db_data: 


secrets:
  db-password:
    file: .secrets/postgres-compose.txt

