name: Smoke-Test
on: push

jobs:
  smoke-test-job:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Build backend and database
       run: |
          pip install -r database/requirements.txt
          pip install -r backend/requirements.txt
          cd backend && make docker-build && cd -
     - name: Build frontend
       run: |
          npm install -g typescript
          cd frontend && make docker-build && cd -
     - name: Run docker-compose and check
       run: |
          rm -rf .secrets || true
          cp -r .github/workflows/.secrets .
          mkdir -p .letsencrypt/live/danieldoescocktails.com
          cd .letsencrypt/live/danieldoescocktails.com 
          openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -batch -out fullchain.pem -keyout privkey.pem && pwd && ls -al
          cd -
          cd .letsencrypt 
          cp ../.github/workflows/.secrets/ssl-dhparams.pem.ci ./ssl-dhparams.pem 
          echo "# placeholder for CI" > options-ssl-nginx.conf && pwd && ls -al
          cd - 
          docker compose up -d
          sleep 2
          docker compose logs 
          curl -k https://localhost/
          curl -k https://localhost:5000/ping
          docker exec database pg_isready

